[phases.setup]
aptPkgs = ["tesseract-ocr", "libtesseract-dev"]
# Specify Python version to ensure pip is available
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
# Install Python dependencies and NLTK data
cmds = [
    "python -m ensurepip --upgrade",
    "python -m pip install --no-cache-dir -r requirements.txt",
    "python -m nltk.downloader punkt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 600"