[phases.setup]
aptPkgs = ["tesseract-ocr", "libtesseract-dev", "gcc", "g++", "make", "libffi-dev", "libssl-dev", "zlib1g-dev"]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
    # Create a virtual environment to avoid PEP 668 restrictions
    "python -m venv /app/venv",
    # Activate virtual environment and install dependencies
    "/app/venv/bin/python -m pip install --no-cache-dir -r requirements.txt",
    "/app/venv/bin/python -m nltk.downloader punkt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT app:app --timeout 600"