[phases.setup]
aptPkgs = ["tesseract-ocr", "libtesseract-dev", "gcc", "g++", "make", "libffi-dev", "libssl-dev", "zlib1g-dev"]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
    # Create virtual environment
    "python -m venv /app/venv",
    # Install dependencies and verify gunicorn
    "/app/venv/bin/python -m pip install --no-cache-dir -r requirements.txt",
    "/app/venv/bin/pip install gunicorn==20.1.0",  # Explicitly install gunicorn
    "/app/venv/bin/pip show gunicorn",  # Debug: Verify gunicorn installation
    "/app/venv/bin/python -m nltk.downloader punkt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "/app/venv/bin/gunicorn --bind 0.0.0.0:$PORT app:app --timeout 600"